#!/usr/bin/env python3
"""
Setup script to inject personal information into training templates.

This script reads personal information from config/config.yaml and adds it to the
beginning of each template file. This helps AI agents generate more suitable
and realistic training plans, workouts, and analyses.

Usage:
    python3 scripts/setup.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from utils import get_config_path, get_repo_root

import yaml


def read_config():
    """Read configuration from config/config.yaml."""
    config_path = get_config_path()
    
    if not config_path.exists():
        print(f"Error: config/config.yaml not found at {config_path}", file=sys.stderr)
        print("Please create config/config.yaml with your personal training information.", file=sys.stderr)
        return None
    
    try:
        with open(config_path, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        return config
    except yaml.YAMLError as e:
        print(f"Error parsing config/config.yaml: {e}", file=sys.stderr)
        return None
    except (IOError, OSError) as e:
        print(f"Error reading config/config.yaml: {e}", file=sys.stderr)
        return None


def format_personal_info_for_goal(config):
    """Format personal information for goal template."""
    lines = []
    
    lines.append("<!-- PERSONAL INFORMATION -->")
    lines.append("<!-- This section is auto-generated by scripts/setup.py from config/config.yaml -->")
    lines.append("<!-- DO NOT EDIT THIS SECTION MANUALLY - Edit config/config.yaml instead -->")
    lines.append("")
    lines.append("## 👤 Personal Information")
    lines.append("")
    
    runner = config.get('athlete') or config.get('runner', {})
    
    # Date of birth only - training preferences go in "Training constraints / preferences" section
    if runner.get('date_of_birth'):
        lines.append(f"- **Date of birth:** {runner['date_of_birth']}")
    
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("<!-- END PERSONAL INFORMATION -->")
    lines.append("")
    
    return "\n".join(lines)


def format_training_preferences_for_goal(config):
    """Format training preferences section for goal template."""
    lines = []
    
    lines.append("<!-- TRAINING PREFERENCES -->")
    lines.append("<!-- This section is auto-generated by scripts/setup.py from config/config.yaml -->")
    lines.append("<!-- DO NOT EDIT THIS SECTION MANUALLY - Edit config/config.yaml instead -->")
    lines.append("")
    lines.append("## Training constraints / preferences")
    
    prefs = config.get('preferences', {})
    
    # Run days
    run_days = prefs.get('run_days', [])
    if run_days:
        days_str = " / ".join(run_days)
        lines.append(f"- Run days: **{days_str}**")
    else:
        lines.append("- Run days: **[Days]**")
    
    # Strength training day
    strength_day = prefs.get('strength_day', '')
    if strength_day:
        lines.append(f"- Strength: typically **{strength_day}** (not tracked in repo)")
    else:
        lines.append("- Strength: typically **[Day]** (not tracked in repo)")
    
    lines.append("- Additional notes: ...")
    lines.append("")
    lines.append("<!-- END TRAINING PREFERENCES -->")
    lines.append("")
    
    return "\n".join(lines)


def format_training_status(config):
    """Format training status for templates."""
    status_config = config.get('training_status', {})
    status = status_config.get('status', 'active')
    
    # If active with no note, return empty (no need to add section)
    if status == 'active' and not status_config.get('note'):
        return None
    
    lines = []
    lines.append("<!-- TRAINING STATUS -->")
    lines.append("<!-- This section is auto-generated by scripts/setup.py from config/config.yaml -->")
    lines.append("<!-- DO NOT EDIT THIS SECTION MANUALLY - Edit config/config.yaml instead -->")
    lines.append("")
    
    # Status emoji mapping
    status_emoji = {
        'active': '🟢',
        'sick': '🤒',
        'injury': '🩹',
        'holidays': '🏖️',
        'returning': '🔄'
    }
    
    emoji = status_emoji.get(status, '⚪')
    lines.append(f"## {emoji} Training Status: {status.title()}")
    lines.append("")
    
    # Add note if present
    if status_config.get('note'):
        lines.append(f"**Note:** {status_config['note']}")
        lines.append("")
    
    # Add AI guidance based on status
    guidance = {
        'sick': "<!-- **AI Coach Guidance:** Runner is currently sick. Prioritize rest and recovery. If training is planned, significantly reduce intensity and volume. Consider skipping workouts entirely if symptoms are severe. -->",
        'injury': "<!-- **AI Coach Guidance:** Runner is currently injured. Avoid exercises that stress the injured area. Focus on recovery and alternative low-impact activities if approved. -->",
        'holidays': "<!-- **AI Coach Guidance:** Runner is on holidays. Plan lighter, flexible workouts that can be done without usual equipment/routes. Maintain base fitness without strict targets. -->",
        'returning': "<!-- **AI Coach Guidance:** Runner is returning from a break. Apply gradual ramp-up protocol: start at 50-60% of previous volume, increase slowly over 2-3 weeks. Avoid intensity work in the first week. -->"
    }
    
    if status in guidance:
        lines.append(guidance[status])
        lines.append("")
    
    lines.append("---")
    lines.append("")
    lines.append("<!-- END TRAINING STATUS -->")
    lines.append("")
    
    return "\n".join(lines)


def format_personal_info_for_week_plan(config):
    """Format personal information for week plan template."""
    lines = []
    
    lines.append("<!-- PERSONAL INFORMATION -->")
    lines.append("<!-- This section is auto-generated by scripts/setup.py from config/config.yaml -->")
    lines.append("<!-- DO NOT EDIT THIS SECTION MANUALLY - Edit config/config.yaml instead -->")
    lines.append("")
    lines.append("## 👤 Personal Information")
    lines.append("")
    
    runner = config.get('athlete') or config.get('runner', {})
    
    # Date of birth
    if runner.get('date_of_birth'):
        lines.append(f"- **Date of birth:** {runner['date_of_birth']}")
    
    # Weight and height
    if runner.get('weight'):
        lines.append(f"- **Weight:** {runner['weight']} kg")
    if runner.get('height'):
        lines.append(f"- **Height:** {runner['height']} cm")
    
    lines.append("")
    lines.append("<!-- **Note for AI Coach:** Use the above personal data (age from date of birth, weight, and height) along with recent workout history and heart rate data to calculate appropriate heart rate zones for this week's training. Consider the athlete's current fitness level, training phase, and the specific goals for this week when determining zone ranges. -->")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("<!-- END PERSONAL INFORMATION -->")
    lines.append("")
    
    return "\n".join(lines)


def format_personal_info_for_workout_analysis(config):
    """Format personal information for workout analysis template."""
    lines = []
    
    lines.append("<!-- PERSONAL INFORMATION -->")
    lines.append("<!-- This section is auto-generated by scripts/setup.py from config/config.yaml -->")
    lines.append("<!-- DO NOT EDIT THIS SECTION MANUALLY - Edit config/config.yaml instead -->")
    lines.append("")
    lines.append("## 👤 Personal Information")
    lines.append("")
    
    runner = config.get('athlete') or config.get('runner', {})
    
    # Date of birth
    if runner.get('date_of_birth'):
        lines.append(f"- **Date of birth:** {runner['date_of_birth']}")
    
    # Weight and height
    if runner.get('weight'):
        lines.append(f"- **Weight:** {runner['weight']} kg")
    if runner.get('height'):
        lines.append(f"- **Height:** {runner['height']} cm")
    
    lines.append("")
    lines.append("<!-- **Note for AI Analyst:** Use the above personal data (age from date of birth, weight, and height) to estimate appropriate heart rate zones for analyzing this workout. Calculate zones based on common formulas (e.g., 220 - age for max HR) and the athlete's physiology. -->")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("<!-- END PERSONAL INFORMATION -->")
    lines.append("")
    
    return "\n".join(lines)


def update_template_section(template_path, section_content, start_marker, end_marker):
    """Update a specific section in a template file marked by HTML comments."""
    if not template_path.exists():
        print(f"Warning: Template not found: {template_path}", file=sys.stderr)
        return False
    
    try:
        # Read current template
        with open(template_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except (IOError, OSError) as e:
        print(f"Error reading template {template_path}: {e}", file=sys.stderr)
        return False
    
    # Check if section already exists
    if start_marker in content:
        # Remove old section
        start_idx = content.find(start_marker)
        end_idx = content.find(end_marker)
        if end_idx != -1:
            # Find the end of the line after the end marker
            end_line = content.find('\n', end_idx)
            if end_line != -1:
                end_idx = end_line + 1
            else:
                end_idx = end_idx + len(end_marker)
            
            # Remove the section
            content = content[:start_idx] + content[end_idx:]
    
    # For PERSONAL INFORMATION section, insert after title
    # For TRAINING PREFERENCES section, insert before "Training roadmap" or at appropriate location
    lines = content.split('\n')
    insert_idx = 0
    
    if "PERSONAL INFORMATION" in start_marker:
        # Insert after first heading
        for i, line in enumerate(lines):
            if line.startswith('#'):
                insert_idx = i + 1
                break
    elif "TRAINING PREFERENCES" in start_marker:
        # Find the "## Training constraints / preferences" line or similar
        for i, line in enumerate(lines):
            if "## Training constraints / preferences" in line or \
               "## Training roadmap" in line or \
               (line.startswith("## ") and "Training" in line and ("constraint" in line.lower() or "preference" in line.lower())):
                insert_idx = i
                # Remove the existing line if it's the section header
                if "## Training constraints / preferences" in line:
                    lines.pop(i)
                    # Also remove following lines until we hit another section or empty lines
                    while i < len(lines) and lines[i].strip() and not lines[i].startswith('#'):
                        lines.pop(i)
                break
        
        if insert_idx == 0:
            # If not found, insert before "Training roadmap"
            for i, line in enumerate(lines):
                if "## Training roadmap" in line:
                    insert_idx = i
                    break
    elif "TRAINING STATUS" in start_marker:
        # Insert after PERSONAL INFORMATION section (after the --- separator)
        # or after the first heading if no personal info section
        found_personal_info_end = False
        for i, line in enumerate(lines):
            if "<!-- END PERSONAL INFORMATION -->" in line:
                insert_idx = i + 1
                found_personal_info_end = True
                break
        
        if not found_personal_info_end:
            # Insert after first heading
            for i, line in enumerate(lines):
                if line.startswith('#'):
                    insert_idx = i + 1
                    break
    
    # Clean up extra blank lines before insertion point
    while insert_idx > 0 and insert_idx < len(lines) and lines[insert_idx - 1].strip() == '':
        lines.pop(insert_idx - 1)
        insert_idx -= 1
    
    # Insert section
    lines.insert(insert_idx, '')
    lines.insert(insert_idx + 1, section_content.rstrip())
    
    # Write updated content
    updated_content = '\n'.join(lines)
    try:
        with open(template_path, 'w', encoding='utf-8') as f:
            f.write(updated_content)
    except (IOError, OSError) as e:
        print(f"Error writing template {template_path}: {e}", file=sys.stderr)
        return False
    
    return True


def update_template(template_path, personal_info):
    """Update a template file with personal information section."""
    return update_template_section(
        template_path, 
        personal_info, 
        "<!-- PERSONAL INFORMATION -->", 
        "<!-- END PERSONAL INFORMATION -->"
    )


def remove_template_section(template_path, start_marker, end_marker):
    """Remove a section from a template file if it exists."""
    if not template_path.exists():
        return True  # Nothing to remove
    
    try:
        with open(template_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except (IOError, OSError):
        return False
    
    if start_marker not in content:
        return True  # Section doesn't exist, nothing to remove
    
    # Find and remove the section
    start_idx = content.find(start_marker)
    end_idx = content.find(end_marker)
    if end_idx != -1:
        # Find the end of the line after the end marker
        end_line = content.find('\n', end_idx)
        if end_line != -1:
            end_idx = end_line + 1
        else:
            end_idx = end_idx + len(end_marker)
        
        # Remove the section and any extra blank lines
        content = content[:start_idx] + content[end_idx:]
        # Clean up multiple blank lines
        while '\n\n\n' in content:
            content = content.replace('\n\n\n', '\n\n')
    
    try:
        with open(template_path, 'w', encoding='utf-8') as f:
            f.write(content)
    except (IOError, OSError):
        return False
    
    return True


def main():
    """Main entry point."""
    print("🏃 Setting up personal training information...")
    print()
    
    # Read configuration
    config = read_config()
    if config is None:
        return 1
    
    print("✅ Configuration loaded successfully")
    
    # Update templates with appropriate personal info
    repo_root = get_repo_root()
    templates_dir = repo_root / "templates"
    
    templates = {
        "goal-template.md": format_personal_info_for_goal,
        "week-plan-template.md": format_personal_info_for_week_plan,
        "workout-analysis-template.md": format_personal_info_for_workout_analysis
    }
    
    updated_count = 0
    for template_name, formatter_func in templates.items():
        template_path = templates_dir / template_name
        print(f"Updating {template_name}...", end=' ')
        
        # Update personal information section
        personal_info = formatter_func(config)
        success = update_template(template_path, personal_info)
        
        # For goal template, also update training preferences section
        if template_name == "goal-template.md" and success:
            training_prefs = format_training_preferences_for_goal(config)
            success = update_template_section(
                template_path,
                training_prefs,
                "<!-- TRAINING PREFERENCES -->",
                "<!-- END TRAINING PREFERENCES -->"
            )
        
        # For week plan template, also update training status section
        if template_name == "week-plan-template.md" and success:
            training_status = format_training_status(config)
            if training_status:  # Only add if status is not 'active' with no note
                success = update_template_section(
                    template_path,
                    training_status,
                    "<!-- TRAINING STATUS -->",
                    "<!-- END TRAINING STATUS -->"
                )
            else:
                # Remove training status section if it exists and status is active
                remove_template_section(
                    template_path,
                    "<!-- TRAINING STATUS -->",
                    "<!-- END TRAINING STATUS -->"
                )
        
        if success:
            print("✅")
            updated_count += 1
        else:
            print("❌")
    
    print()
    print(f"✅ Updated {updated_count}/{len(templates)} templates")
    print()
    print("📝 Personal information has been added to all templates.")
    print("   AI agents will now use this information for better training plans!")
    print()
    print("💡 To update the information:")
    print("   1. Edit config/config.yaml with your latest data")
    print("   2. Run: python3 scripts/setup.py")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
